platform :ios, '8.0'
use_frameworks!

target ‘Biin’ do
pod 'Fabric'
pod 'Crashlytics'
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'UberRides'
pod 'KontaktSDK', '~> 1.0'
pod 'Firebase'
pod 'Firebase/Messaging’
end