# Uncomment this line to define a global platform for your project
#platform :ios, '8.0'
# Uncomment this line if you're using Swift
#use_frameworks!


platform :ios, '8.0'
use_frameworks!

target ‘biin’ do
pod 'UberRides'
pod 'KontaktSDK', '~> 1.0'
end