platform :ios, '8.0'
use_frameworks!

target ‘Biin’ do
pod 'Fabric'
pod 'Crashlytics'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'UberRides'
pod 'KontaktSDK', '~> 1.0'
pod 'Firebase'
pod 'Firebase/Messaging’
end