platform :ios, '8.0'
use_frameworks!

target ‘Biin’ do
pod 'Fabric'
pod 'Crashlytics'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'UberRides'
pod 'KontaktSDK', '~> 1.0'
pod 'Firebase'
pod 'Firebase/Messaging’
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '2.3'
        end
    end
  end